# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20170504_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_of_document',
            field=models.CharField(choices=[('BankTransfer', 'Bank Transfer'), ('BankStatement', 'Account Statement'), ('Undefined', 'Undefined'), ('W2', 'Wage and Tax Statement')], default='Undefined', max_length=10),
        ),
    ]
