# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20170504_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_of_document',
            field=models.CharField(choices=[('W2', 'Wage and Tax Statement'), ('BankStatement', 'Account Statement'), ('Undefined', 'Undefined'), ('BankTransfer', 'Bank Transfer')], default='Undefined', max_length=10),
        ),
    ]
