# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170504_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_of_document',
            field=models.CharField(choices=[('BankTransfer', 'Bank Transfer'), ('Undefined', 'Undefined'), ('W2', 'Wage and Tax Statement'), ('BankStatement', 'Account Statement')], default='Undefined', max_length=20),
        ),
    ]
