# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20170505_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_of_document',
            field=models.CharField(choices=[('W2', 'Wage and Tax Statement'), ('Undefined', 'Undefined'), ('BankStatement', 'Account Statement'), ('BankTransfer', 'Bank Transfer')], default='Undefined', max_length=20),
        ),
        migrations.AlterField(
            model_name='error',
            name='type_of_error',
            field=models.CharField(choices=[('encrypted', 'File Password Protected'), ('corrupted', 'File Cannot Be Opened'), ('clean', 'No Errors detected')], default='clean', max_length=30),
        ),
    ]
