# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20170505_2252'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='document',
            managers=[
                ('DocumentManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='type_of_document',
            field=models.CharField(choices=[('BankStatement', 'Account Statement'), ('Undefined', 'Undefined'), ('W2', 'Wage and Tax Statement'), ('BankTransfer', 'Bank Transfer')], default='Undefined', max_length=20),
        ),
        migrations.AlterField(
            model_name='error',
            name='type_of_error',
            field=models.CharField(choices=[('encrypted', 'File Password Protected'), ('corrupted', 'File Cannot Be Opened'), ('clean', 'No Errors detected')], default='clean', max_length=30),
        ),
    ]
