# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20170506_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_text',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_of_document',
            field=models.CharField(choices=[('Undefined', 'Undefined'), ('W2', 'Wage and Tax Statement'), ('BankStatement', 'Account Statement'), ('BankTransfer', 'Bank Transfer')], default='Undefined', max_length=20),
        ),
        migrations.AlterField(
            model_name='error',
            name='type_of_error',
            field=models.CharField(choices=[('corrupted', 'File Cannot Be Opened'), ('encrypted', 'File Password Protected'), ('clean', 'No Errors detected')], default='clean', max_length=30),
        ),
    ]
