# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20170506_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_text',
            field=models.TextField(blank=True, max_length=25000),
        ),
    ]
